### ISSUE TITLE
Interp method thread safety

### ISSUE THREAD

**Issue by ghansham** [rncarpio/linterp#3]
Is the interp method thread safe for multilinear class?

Regards
Ghansham

**Comment by leonleon33156** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ghansham** [comment]
Really sorry but I could not make out as the reply is not in English.

**Comment by ghansham** [comment]
Really sorry but I could not make out as the reply is not in English.

**Comment by rncarpio** [comment]
> Is the interp method thread safe for multilinear class?
> 
> Regards Ghansham

yes, it is MT safe

**Comment by ghansham** [comment]
Thanks a lot. I must say that it is a wonderful library. Just one suggestion. The interp_vec function can be modified to make use of multi-core architecture and number of threads to be used can also be configured using some utility functions. Easiest approach could be using openmp pragma.
